"use client";

import { useEffect, useMemo, useState } from "react";
import { badge, coverage, materialShortfall, money, totalAtRisk } from "@/lib/operations";
import type { IncidentStage, OperationalState, RecoveryPlan, Status } from "@/lib/models";
import { useOperations } from "@/components/operations-provider";

const nav = ["Overview", "Orders", "Inventory", "Suppliers", "Production", "Incidents"] as const;
type Page = typeof nav[number];

function Pill({ status }: { status: Status | string }) {
  const styles: Record<string, string> = { healthy: "bg-emerald-50 text-emerald-700", scheduled: "bg-slate-100 text-slate-600", watch: "bg-amber-50 text-amber-700", "at-risk": "bg-orange-50 text-orange-700", blocked: "bg-red-50 text-red-700", critical: "bg-red-50 text-red-700" };
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold uppercase tracking-wide ${styles[status] || "bg-slate-100 text-slate-600"}`}>{badge(status)}</span>;
}
function Panel({ title, action, children, className = "" }: { title: string; action?: React.ReactNode; children: React.ReactNode; className?: string }) {
  return <section className={`rounded-xl border border-[#e6e9e7] bg-white ${className}`}><div className="flex items-center justify-between border-b border-[#edf0ee] px-5 py-4"><h2 className="text-sm font-bold tracking-tight text-[#16201d]">{title}</h2>{action}</div>{children}</section>;
}
function MaterialName({ id, state }: { id: string; state: OperationalState }) { return <>{state.materials.find(m => m.id === id)?.name ?? id}</>; }
function SummaryCards({ items }: { items: { label: string; value: string; note: string; status?: Status }[] }) { return <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map(item => <div key={item.label} className="rounded-xl border border-[#e6e9e7] bg-white px-4 py-3.5"><p className="text-[10px] font-bold uppercase tracking-[.11em] text-[#71807b]">{item.label}</p><div className="mt-2 flex items-center justify-between gap-2"><b className="text-lg tracking-tight">{item.value}</b>{item.status && <Pill status={item.status}/>}</div><p className="mt-1 text-xs text-[#71807b]">{item.note}</p></div>)}</div>; }
const stageLabel: Record<IncidentStage, string> = { incident_detected: "Incident detected", impact_calculated: "Impact calculated", investigation_in_progress: "Investigation in progress", recovery_plan_proposed: "Recovery plan proposed", awaiting_human_approval: "Awaiting human approval", recovery_approved: "Recovery approved", purchase_order_created: "Purchase order created", production_rescheduled: "Production rescheduled", recovery_executed: "Recovery executed", incident_mitigated: "Incident mitigated" };

function currentRecoveryPlan(state: OperationalState, incident: OperationalState["incidents"][number]) {
  const plans = state.recoveryPlans.filter((plan) => plan.incidentId === incident.id);
  const latestMatching = (predicate: (plan: RecoveryPlan) => boolean) => [...plans].reverse().find(predicate);
  if (incident.stage === "awaiting_human_approval") return latestMatching((plan) => plan.approvalState === "pending");
  if (incident.stage === "recovery_approved") return latestMatching((plan) => plan.approvalState === "approved" && plan.executionState === "not_executed");
  if (incident.stage === "recovery_executed" || incident.stage === "incident_mitigated") return latestMatching((plan) => plan.executionState === "executed");
  if (incident.stage === "recovery_plan_proposed") return latestMatching((plan) => plan.approvalState === "not_requested");
  if (incident.stage === "impact_calculated") return latestMatching((plan) => plan.approvalState === "rejected") ?? plans.at(-1);
  return plans.at(-1);
}

export default function ControlRoom() {
  const [page, setPage] = useState<Page>("Overview");
  const [reviewPlanId, setReviewPlanId] = useState<string | null>(null);
  const { state, resetDemo, webMcpStatus, webMcpError } = useOperations();
  const [lastReset, setLastReset] = useState<string | null>(null);
  const active = state.incidents.find(i => i.id === "inc-01")!;
  const supplier = state.suppliers.find(s => s.id === active.supplierId)!;
  const material = state.materials.find(m => m.id === active.materialId)!;
  const atRisk = useMemo(() => state.orders.filter(o => o.risk === "critical" || o.risk === "at-risk"), [state]);
  const reset = () => { resetDemo(); setReviewPlanId(null); setLastReset(new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })); };
  const webMcpLabel = { checking: "WebMCP checking", ready: "WebMCP Ready", unavailable: "WebMCP Unavailable", error: "WebMCP registration error" }[webMcpStatus];
  const reviewPlan = reviewPlanId ? state.recoveryPlans.find((plan) => plan.id === reviewPlanId) : undefined;

  return <main className="min-h-screen bg-[#f6f7f5] text-[#16201d]">
    <aside className="fixed inset-y-0 left-0 z-10 hidden w-60 border-r border-[#dfe4e0] bg-[#173530] px-4 py-6 text-white lg:flex lg:flex-col">
      <div className="mb-11 px-3"><div className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg bg-[#76c9b5] text-base font-black text-[#173530]">O</div><p className="text-sm font-semibold tracking-tight">OpsRelay</p><p className="mt-1 text-xs leading-4 text-[#9db8b1]">Human-guided incident recovery for agentic operations</p><p className="mt-2 text-[11px] text-[#7fa098]">Parker &amp; Rowe Manufacturing</p></div>
      <nav className="space-y-1">{nav.map(item => <button key={item} onClick={() => setPage(item)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm transition ${page === item ? "bg-white/12 font-semibold text-white" : "text-[#b2c7c1] hover:bg-white/8 hover:text-white"}`}><span className={`h-2 w-2 rounded-full ${item === "Incidents" ? "bg-[#f5b873]" : "bg-current opacity-60"}`}/>{item}</button>)}</nav>
      <div className="mt-auto rounded-lg border border-white/10 bg-white/5 p-3 text-xs text-[#b9cbc6]"><p className="font-semibold text-white">Simulation mode</p><p className="mt-1 leading-5">No external APIs. State is deterministic and local.</p><div className="mt-2.5 flex items-center gap-2 border-t border-white/10 pt-2.5" title={webMcpError ?? undefined}><span className={`h-1.5 w-1.5 rounded-full ${webMcpStatus === "ready" ? "bg-[#76c9b5]" : webMcpStatus === "error" ? "bg-[#f19a9f]" : "bg-[#91a9a3]"}`}/><span>{webMcpLabel}</span></div></div>
    </aside>
    <div className="lg:pl-60">
      <header className="sticky top-0 z-10 flex h-[73px] items-center justify-between border-b border-[#e1e5e2] bg-[#f6f7f5]/95 px-5 backdrop-blur lg:px-9"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[#71807b]">Thursday, 28 August · 08:45 SAST</p><h1 className="mt-0.5 text-xl font-bold tracking-tight">{page}</h1></div><div className="flex items-center gap-3"><span className="hidden text-xs text-[#71807b] sm:inline">Last refresh: just now</span><button onClick={reset} className="rounded-lg border border-[#cdd5d1] bg-white px-3.5 py-2 text-sm font-semibold text-[#25443d] shadow-sm hover:bg-[#f3f8f6]">↻ Reset Demo</button></div></header>
      <div className="mx-auto max-w-[1600px] p-5 lg:p-8">{page === "Overview" ? <Overview state={state} active={active} supplier={supplier.name} material={material.name} atRisk={atRisk} onReviewPlan={setReviewPlanId} /> : <DetailPage page={page} state={state} onReviewPlan={setReviewPlanId} />}{lastReset && <p className="mt-5 text-center text-xs text-[#71807b]">Demo reset to original scenario at {lastReset}.</p>}</div>
    </div>
    {reviewPlan && <RecoveryPlanReviewModal plan={reviewPlan} state={state} onClose={() => setReviewPlanId(null)} />}
  </main>;
}

function RecoveryPlanReviewModal({ plan, state, onClose }: { plan: RecoveryPlan; state: OperationalState; onClose: () => void }) {
  const { runtime } = useOperations();
  const supplier = state.suppliers.find((item) => item.id === plan.supplierId)!;
  const material = state.materials.find((item) => item.id === plan.materialId)!;
  const orders = plan.ordersProtected.map((orderId) => state.orders.find((order) => order.id === orderId)).filter(Boolean);
  const scheduleImpact = plan.scheduleChanges.length
    ? plan.scheduleChanges.map((change) => `${state.jobs.find((job) => job.id === change.jobId)?.number}: ${change.fromStartTime}–${change.fromEndTime} → ${change.toStartTime}–${change.toEndTime}`).join(" · ")
    : "No schedule movement required; recovery material is expected before affected production begins.";

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); };
    document.addEventListener("keydown", onKeyDown);
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => { document.removeEventListener("keydown", onKeyDown); document.body.style.overflow = previousOverflow; };
  }, [onClose]);

  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#10211d]/55 p-0 backdrop-blur-[2px] sm:items-center sm:p-6" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <section role="dialog" aria-modal="true" aria-labelledby="recovery-plan-title" className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-2xl border border-[#dfe5e1] bg-white shadow-2xl sm:rounded-2xl">
      <div className="flex items-start justify-between gap-4 border-b border-[#e8ece9] px-5 py-5 sm:px-7"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#fff1d7] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.12em] text-[#815b1f]">Human decision required</span><span className="font-mono text-xs font-semibold text-[#71807b]">{plan.id}</span></div><h2 id="recovery-plan-title" className="mt-3 text-xl font-bold tracking-tight">Review Recovery Plan</h2><p className="mt-1 text-sm leading-6 text-[#66736e]">Review the operational and financial impact before authorizing the agent to execute this plan.</p></div><button autoFocus onClick={onClose} aria-label="Close recovery plan review" className="rounded-lg border border-[#dfe5e1] px-3 py-1.5 text-lg leading-none text-[#61716b] hover:bg-[#f5f7f6]">×</button></div>
      <div className="space-y-5 px-5 py-5 sm:px-7 sm:py-6">
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl bg-[#f7f9f8] p-3.5"><p className="text-[10px] font-bold uppercase tracking-wide text-[#71807b]">Supplier</p><b className="mt-1 block text-sm">{supplier.name}</b></div><div className="rounded-xl bg-[#f7f9f8] p-3.5"><p className="text-[10px] font-bold uppercase tracking-wide text-[#71807b]">Material</p><b className="mt-1 block text-sm">{material.name}</b></div><div className="rounded-xl bg-[#f7f9f8] p-3.5"><p className="text-[10px] font-bold uppercase tracking-wide text-[#71807b]">Quantity</p><b className="mt-1 block text-sm">{plan.quantityKg.toLocaleString()} kg</b></div><div className="rounded-xl bg-[#f7f9f8] p-3.5"><p className="text-[10px] font-bold uppercase tracking-wide text-[#71807b]">Delivery method</p><b className="mt-1 block text-sm">{plan.expedited ? "Expedited delivery" : "Standard delivery"}</b></div></div>
        <div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-[#71807b]">Total recovery cost</p><b className="mt-1 block text-lg">{money(plan.totalRecoveryCost)}</b></div><div><p className="text-xs text-[#71807b]">Orders protected</p><b className="mt-1 block text-lg">{orders.length}</b><p className="mt-1 text-xs text-[#71807b]">{orders.map((order) => order?.number).join(" · ") || "None"}</p></div><div><p className="text-xs text-[#71807b]">Financial exposure avoided</p><b className="mt-1 block text-lg text-[#0b7262]">{money(plan.estimatedExposureAvoided)}</b></div></div>
        <div className="rounded-xl border border-[#e4e9e6] p-4"><p className="text-xs font-bold uppercase tracking-[.1em] text-[#53645e]">Schedule impact</p><p className="mt-2 text-sm leading-6 text-[#66736e]">{scheduleImpact}</p></div>
        <div className="rounded-xl border border-[#d9e8e3] bg-[#f4faf8] p-4"><p className="text-xs font-bold uppercase tracking-[.1em] text-[#246c5d]">What execution will change</p><p className="mt-2 text-sm leading-6 text-[#53645e]">After human approval, the agent may create a {money(plan.totalRecoveryCost)} purchase order with {supplier.name}, add {plan.quantityKg.toLocaleString()} kg to incoming {material.name} inventory, apply the listed production schedule changes, recalculate {orders.length} customer order risks, and update the incident status. Approval alone makes none of these operational changes.</p></div>
        {plan.approvalState === "pending" && <div className="rounded-xl border border-[#ead9b8] bg-[#fffaf0] p-4 text-sm text-[#725522]"><b>Human approval required.</b> The agent cannot approve this proposal and execution will remain blocked until you approve it here.</div>}
        {plan.approvalState === "approved" && <div className="rounded-xl border border-[#b9dfd4] bg-[#edf8f4] p-4 text-sm font-bold text-[#0b7262]">Human approved — ready for agent execution.</div>}
        {plan.approvalState === "rejected" && <div className="rounded-xl border border-[#efc6cc] bg-[#fff6f7] p-4 text-sm font-bold text-[#9b3542]">Recovery plan rejected by the human operator. Execution remains blocked.</div>}
      </div>
      <div className="flex flex-col-reverse gap-2 border-t border-[#e8ece9] bg-[#fbfcfb] px-5 py-4 sm:flex-row sm:justify-end sm:px-7"><button onClick={onClose} className="rounded-lg border border-[#d7dfdb] bg-white px-4 py-2.5 text-sm font-semibold text-[#42534d] hover:bg-[#f5f7f6]">Close</button>{plan.approvalState === "pending" && <><button onClick={() => runtime.recordHumanApproval(plan.id, false)} className="rounded-lg border border-[#d8bfc3] bg-white px-4 py-2.5 text-sm font-semibold text-[#8f3540] hover:bg-[#fff5f6]">Reject Recovery Plan</button><button onClick={() => runtime.recordHumanApproval(plan.id, true)} className="rounded-lg bg-[#0b7262] px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-[#095f52]">Approve Recovery Plan</button></>}</div>
    </section>
  </div>;
}

function Overview({ state, active, supplier, material, atRisk, onReviewPlan }: { state: OperationalState; active: OperationalState["incidents"][number]; supplier: string; material: string; atRisk: OperationalState["orders"]; onReviewPlan: (planId: string) => void }) {
  const activePlan = currentRecoveryPlan(state, active);
  const productionRecovered = !state.jobs.some((job) => job.status === "blocked" || job.status === "at-risk");
  const recoveryMessage = active.status === "mitigated" ? "Recovery executed — all affected commitments are protected." : activePlan?.approvalState === "approved" ? "Human approved — ready for agent execution." : activePlan?.approvalState === "pending" ? "Recovery plan submitted — human approval required." : activePlan?.approvalState === "rejected" ? "Recovery plan rejected — execution is blocked and a different simulation may be proposed." : activePlan ? "Recovery plan proposed — approval has not been requested." : "Recovery required — no recovery plan has been approved.";
  const metrics = [{ label: "Production Health", value: productionRecovered ? "Recovered" : "Constrained", note: productionRecovered ? "Tomorrow’s jobs protected" : "3 jobs affected tomorrow", status: productionRecovered ? "healthy" : "critical" }, { label: "Orders At Risk", value: String(totalAtRisk(state)), note: totalAtRisk(state) ? "Requires recovery action" : "Affected orders protected", status: totalAtRisk(state) ? "at-risk" : "healthy" }, { label: "Critical Materials", value: state.inventory.filter((item) => item.status === "critical" || item.status === "at-risk").length.toString(), note: active.status === "mitigated" ? "Incoming recovery stock secured" : "Aluminium coverage short", status: active.status === "mitigated" ? "healthy" : "critical" }, { label: "Estimated Financial Impact", value: money(active.estimatedImpact), note: active.estimatedImpact ? "Revenue exposed" : "Exposure avoided", status: active.estimatedImpact ? "at-risk" : "healthy" }];
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(m => <div key={m.label} className="rounded-xl border border-[#e6e9e7] bg-white p-5 shadow-[0_1px_1px_rgba(0,0,0,.02)]"><p className="text-xs font-semibold uppercase tracking-[0.1em] text-[#71807b]">{m.label}</p><div className="mt-3 flex items-end justify-between"><p className="text-2xl font-bold tracking-tight">{m.value}</p><Pill status={m.status}/></div><p className="mt-3 text-xs text-[#71807b]">{m.note}</p></div>)}</div>
    <section className={`rounded-xl border p-5 shadow-sm ${active.status === "mitigated" ? "border-[#b9dfd4] bg-[#f8fdfb]" : "border-[#f1c1c8] bg-[#fffafb]"}`}><div className="flex flex-col justify-between gap-4 md:flex-row"><div><div className="flex items-center gap-2"><span className={`flex h-6 w-6 items-center justify-center rounded-full text-xs font-bold text-white ${active.status === "mitigated" ? "bg-[#0b7262]" : "bg-[#bb3545]"}`}>{active.status === "mitigated" ? "✓" : "!"}</span><p className={`text-xs font-bold uppercase tracking-[.12em] ${active.status === "mitigated" ? "text-[#0b7262]" : "text-[#a12e3d]"}`}>{active.status === "mitigated" ? "Incident mitigated" : "Active incident · Critical"}</p></div><h2 className="mt-3 text-lg font-bold">{active.title}</h2><p className="mt-1 text-sm text-[#59645f]"><b>{supplier}</b> has delayed <b>{material}</b> by <b>48 hours</b>.</p></div><div className="grid grid-cols-2 gap-x-8 gap-y-3 text-sm sm:grid-cols-3"><div><p className="text-xs text-[#71807b]">Affected jobs</p><b>{active.affectedJobIds.length}</b></div><div><p className="text-xs text-[#71807b]">Affected orders</p><b>{active.affectedOrderIds.length}</b></div><div><p className="text-xs text-[#71807b]">Estimated impact</p><b>{money(active.estimatedImpact)}</b></div></div></div><div className={`mt-4 flex flex-col gap-3 border-t pt-3 text-sm sm:flex-row sm:items-center sm:justify-between ${active.status === "mitigated" ? "border-[#d6ebe5] text-[#246c5d]" : "border-[#f5d9dc] text-[#7e3b45]"}`}><b>{recoveryMessage}</b><div className="flex flex-wrap items-center gap-3">{activePlan?.approvalState === "pending" && <button onClick={() => onReviewPlan(activePlan.id)} className="rounded-lg bg-[#7e3b45] px-4 py-2 text-xs font-bold text-white shadow-sm hover:bg-[#682f38]">Review Recovery Plan</button>}<span className="text-xs font-semibold uppercase tracking-wide">{stageLabel[active.stage]}</span></div></div></section>
    <div className="grid gap-6 xl:grid-cols-[1.65fr_1fr]"><Panel title="Tomorrow’s Production Timeline" action={<span className="text-xs text-[#71807b]">06:00 — 20:00</span>}><div className="divide-y divide-[#edf0ee]">{state.jobs.map(job => <div key={job.id} className="grid gap-3 px-5 py-4 sm:grid-cols-[80px_1fr_auto]"><div className="text-sm font-bold text-[#36564e]">{job.startTime}<span className="block text-xs font-normal text-[#71807b]">{job.endTime}</span></div><div><div className="flex items-center gap-2"><b className="text-sm">{job.number}</b><Pill status={job.status}/></div><p className="mt-1 text-sm text-[#4b5954]">{job.product} <span className="text-[#83908b]">· {job.quantity} units</span></p><p className="mt-1 text-xs text-[#71807b]">{job.requiredMaterials.map(r => `${state.materials.find(m => m.id === r.materialId)?.name.split(" ")[0]} ${r.quantity} ${state.materials.find(m => m.id === r.materialId)?.unit}`).join(" · ")}</p></div><div className={`hidden h-2 self-center rounded-full sm:block ${job.status === "blocked" ? "w-20 bg-[#e9a3ac]" : job.status === "at-risk" ? "w-14 bg-[#f6c48b]" : "w-9 bg-[#9dd7c8]"}`}/></div>)}</div></Panel>
      <Panel title="Agent Activity" action={<span className="rounded-full bg-[#eef5f2] px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-[#347061]">Tool activity</span>}><div className="max-h-[430px] overflow-y-auto p-5">{state.activities.map(a => <div className="relative border-l border-[#dce4e0] pb-5 pl-4 last:pb-0" key={a.id}><span className={`absolute -left-[4px] top-1 h-2 w-2 rounded-full ${a.tone === "alert" ? "bg-[#c45a65]" : a.tone === "success" ? "bg-[#0b8a72]" : "bg-[#5d9e8e]"}`}/><div className="flex justify-between gap-3"><b className="text-xs">{a.actor}</b><span className="text-xs text-[#8b9692]">{a.timestamp}</span></div><p className="mt-1 text-xs leading-5 text-[#60706a]">{a.message}</p></div>)}</div></Panel></div>
    <div className="grid gap-6 xl:grid-cols-[1.25fr_1fr]"><Panel title="At-Risk Orders" action={<span className="text-xs font-semibold text-[#0b7262]">View all orders</span>}><Table><thead><tr><Th>Order</Th><Th>Customer</Th><Th>Deadline</Th><Th>Revenue</Th><Th>Risk</Th></tr></thead><tbody>{atRisk.map(o => <tr key={o.id}><Td><b>{o.number}</b><span>{o.product} · {o.quantity} units</span></Td><Td>{o.customer}</Td><Td>{o.deadline}</Td><Td>{money(o.revenue)}</Td><Td><Pill status={o.risk}/></Td></tr>)}</tbody></Table></Panel>
      <Panel title="Inventory Health"><div className="divide-y divide-[#edf0ee]">{state.inventory.map(item => <div className="px-5 py-3.5" key={item.materialId}><div className="flex justify-between gap-3"><div><b className="text-sm"><MaterialName id={item.materialId} state={state}/></b><p className="mt-0.5 text-xs text-[#71807b]">{item.currentStock.toLocaleString()} on hand · {item.reservedStock.toLocaleString()} reserved</p></div><div className="text-right"><Pill status={item.status}/><p className="mt-1 text-xs text-[#71807b]">{coverage(item).toFixed(1)} days free coverage</p></div></div><div className="mt-2 h-1.5 overflow-hidden rounded bg-[#edf1ef]"><div className={`h-full rounded ${item.status === "at-risk" ? "bg-[#dc787f]" : "bg-[#63ad9a]"}`} style={{ width: `${Math.min(100, (item.currentStock / (item.reorderThreshold * 3)) * 100)}%` }}/></div></div>)}</div></Panel></div>
    <Panel title="Alternative Suppliers · Aluminium 6061 Sheet" action={<span className="text-xs text-[#71807b]">{materialShortfall(state, "al-6061").toLocaleString()} kg shortfall</span>}><Table><thead><tr><Th>Supplier</Th><Th>Unit price</Th><Th>Available</Th><Th>Lead time</Th><Th>Expedite</Th><Th>Reliability</Th><Th>MOQ</Th></tr></thead><tbody>{state.quotes.filter(q => q.materialId === "al-6061").map(q => { const s = state.suppliers.find(x => x.id === q.supplierId)!; return <tr key={q.id}><Td><b>{s.name}</b><span>{s.city}</span></Td><Td>{money(q.unitPrice)}/kg</Td><Td>{q.availableQuantity.toLocaleString()} kg</Td><Td>{q.leadTimeHours}h</Td><Td>{q.expeditedLeadTimeHours ? <><b className="text-[#0b7262]">{q.expeditedLeadTimeHours}h</b><span>{money(q.expeditedDeliveryCost ?? 0)} delivery</span></> : <span>Not available</span>}</Td><Td>{s.reliability}%</Td><Td>{q.minimumOrderQuantity.toLocaleString()} kg</Td></tr>})}</tbody></Table></Panel>
  </div>;
}

function DetailPage({ page, state, onReviewPlan }: { page: Page; state: OperationalState; onReviewPlan: (planId: string) => void }) {
  const atRiskOrders = state.orders.filter(order => order.risk === "critical" || order.risk === "at-risk");
  const atRiskRevenue = atRiskOrders.reduce((total, order) => total + order.revenue, 0);
  const criticalInventory = state.inventory.filter(item => item.status === "critical" || item.status === "at-risk");
  const watchInventory = state.inventory.filter(item => item.status === "watch");
  const incomingInventory = state.inventory.reduce((total, item) => total + item.incomingStock, 0);
  const lowestCoverage = Math.min(...state.inventory.map(coverage));
  const blockedJobs = state.jobs.filter(job => job.status === "blocked");
  const atRiskCapacity = state.jobs.filter(job => job.status === "blocked" || job.status === "at-risk").reduce((total, job) => total + job.quantity, 0);
  const aluminiumQuotes = state.quotes.filter(quote => quote.materialId === "al-6061");
  const shortage = materialShortfall(state, "al-6061");
  const fastestQuote = [...aluminiumQuotes].sort((a, b) => (a.expeditedLeadTimeHours ?? a.leadTimeHours) - (b.expeditedLeadTimeHours ?? b.leadTimeHours))[0];
  const mostReliableSupplier = [...state.suppliers].sort((a, b) => b.reliability - a.reliability)[0];
  const fullCoverageCount = aluminiumQuotes.filter(quote => quote.availableQuantity >= shortage).length;
  const primaryIncident = state.incidents.find((incident) => incident.id === "inc-01")!;
  const activePlan = currentRecoveryPlan(state, primaryIncident);
  const content: Record<Exclude<Page, "Overview">, { title: string; subtitle: string; rows: React.ReactNode }> = {
    Orders: { title: "Customer orders", subtitle: "Delivery commitments and current operational risk.", rows: <><SummaryCards items={[{ label: "Open orders", value: String(state.orders.length), note: "Across the active schedule" }, { label: "Revenue exposed", value: money(atRiskRevenue), note: "Across at-risk commitments", status: "at-risk" }, { label: "Orders at risk", value: String(atRiskOrders.length), note: "Need recovery action", status: "critical" }, { label: "Next critical deadline", value: "Tomorrow · 14:00", note: "SO-10482 · Atlas Build" }]} /><Table><thead><tr><Th>Order</Th><Th>Customer</Th><Th>Product</Th><Th>Deadline</Th><Th>Revenue</Th><Th>Status</Th></tr></thead><tbody>{state.orders.map(o => <tr key={o.id}><Td><b>{o.number}</b></Td><Td>{o.customer}</Td><Td>{o.product} · {o.quantity}</Td><Td>{o.deadline}</Td><Td>{money(o.revenue)}</Td><Td><Pill status={o.risk}/></Td></tr>)}</tbody></Table></> },
    Inventory: { title: "Material inventory", subtitle: "Available, reserved, incoming and coverage-based material health.", rows: <><SummaryCards items={[{ label: "Critical materials", value: String(criticalInventory.length), note: "Below available coverage", status: "critical" }, { label: "Materials on watch", value: String(watchInventory.length), note: "Monitor consumption", status: "watch" }, { label: "Incoming inventory", value: incomingInventory.toLocaleString(), note: "Across open purchase orders" }, { label: "Lowest coverage", value: `${lowestCoverage.toFixed(1)} days`, note: "Aluminium 6061 Sheet", status: "at-risk" }]} /><Table><thead><tr><Th>Material</Th><Th>On hand</Th><Th>Reserved</Th><Th>Incoming</Th><Th>Reorder point</Th><Th>Coverage</Th><Th>Status</Th></tr></thead><tbody>{state.inventory.map(i => <tr key={i.materialId}><Td><b><MaterialName id={i.materialId} state={state}/></b></Td><Td>{i.currentStock.toLocaleString()}</Td><Td>{i.reservedStock.toLocaleString()}</Td><Td>{i.incomingStock.toLocaleString()}</Td><Td>{i.reorderThreshold.toLocaleString()}</Td><Td>{coverage(i).toFixed(1)} days</Td><Td><Pill status={i.status}/></Td></tr>)}</tbody></Table></> },
    Suppliers: { title: "Supplier network", subtitle: "Qualified aluminium alternatives with delivery and commercial trade-offs.", rows: <><SummaryCards items={[{ label: "Qualified suppliers", value: String(state.suppliers.length), note: "Approved supplier network" }, { label: "Fastest alternative", value: `${fastestQuote.expeditedLeadTimeHours}h`, note: `${state.suppliers.find(s => s.id === fastestQuote.supplierId)?.name} expedited` }, { label: "Best reliability", value: `${mostReliableSupplier.reliability}%`, note: mostReliableSupplier.name }, { label: "Cover full shortfall", value: String(fullCoverageCount), note: `${shortage.toLocaleString()} kg required` }]} /><Table><thead><tr><Th>Supplier</Th><Th>Location</Th><Th>Available</Th><Th>Price</Th><Th>Standard</Th><Th>Expedited</Th><Th>Reliability</Th><Th>MOQ</Th></tr></thead><tbody>{aluminiumQuotes.map(q => { const s = state.suppliers.find(x => x.id === q.supplierId)!; return <tr key={q.id}><Td><b>{s.name}</b></Td><Td>{s.city}</Td><Td>{q.availableQuantity.toLocaleString()} kg</Td><Td>{money(q.unitPrice)}/kg</Td><Td>{q.leadTimeHours}h</Td><Td>{q.expeditedLeadTimeHours ? <><b>{q.expeditedLeadTimeHours}h</b><span>{money(q.expeditedDeliveryCost ?? 0)} delivery</span></> : "Unavailable"}</Td><Td>{s.reliability}%</Td><Td>{q.minimumOrderQuantity.toLocaleString()} kg</Td></tr> })}</tbody></Table></> },
    Production: { title: "Production schedule", subtitle: "Tomorrow’s planned jobs, material requirements and schedule feasibility.", rows: <><SummaryCards items={[{ label: "Jobs scheduled", value: String(state.jobs.length), note: "Tomorrow’s production plan" }, { label: "Jobs blocked", value: String(blockedJobs.length), note: "Awaiting material coverage", status: "critical" }, { label: "Capacity at risk", value: `${atRiskCapacity} units`, note: "Blocked or constrained jobs", status: "at-risk" }, { label: "Earliest blocked job", value: blockedJobs[0]?.startTime ?? "—", note: blockedJobs[0]?.number ?? "No blocked jobs" }]} /><Table><thead><tr><Th>Job</Th><Th>Product</Th><Th>Schedule</Th><Th>Quantity</Th><Th>Required materials</Th><Th>Status</Th></tr></thead><tbody>{state.jobs.map(j => <tr key={j.id}><Td><b>{j.number}</b></Td><Td>{j.product}</Td><Td>{j.startTime} – {j.endTime}</Td><Td>{j.quantity}</Td><Td>{j.requiredMaterials.map(m => `${m.quantity} ${state.materials.find(x => x.id === m.materialId)?.unit} ${state.materials.find(x => x.id === m.materialId)?.name.split(" ")[0]}`).join(" · ")}</Td><Td><Pill status={j.status}/></Td></tr>)}</tbody></Table></> },
    Incidents: { title: "Operational incidents", subtitle: "Resettable operational scenarios and their current response stage.", rows: <div className="divide-y divide-[#edf0ee]">{state.incidents.map(i => {
      const isPrimaryIncident = i.id === primaryIncident.id;
      const incidentMessage = !isPrimaryIncident
        ? `${i.affectedJobIds.length} production job and ${i.affectedOrderIds.length} customer order currently linked for monitoring.`
        : i.status === "mitigated"
          ? "Approved recovery executed; inventory, production and customer commitments were recalculated."
          : activePlan?.approvalState === "pending"
            ? "Recovery plan submitted — human approval required."
            : activePlan?.approvalState === "approved"
              ? "Human approved — ready for agent execution."
              : activePlan?.approvalState === "rejected"
                ? "Recovery plan rejected — execution remains blocked."
                : i.stage === "impact_calculated"
                  ? "Impact mapped across supplier, inventory, orders and production. Recovery has not been planned."
                  : `Operational recovery workflow is at: ${stageLabel[i.stage].toLowerCase()}.`;
      return <div className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center" key={i.id}><div><div className="flex gap-2"><Pill status={i.severity}/><span className="text-xs font-semibold uppercase tracking-wide text-[#71807b]">{i.status}</span></div><h3 className="mt-2 text-sm font-bold">{i.title}</h3><p className="mt-1 text-xs text-[#71807b]">{incidentMessage}</p></div><div className="flex shrink-0 flex-col items-start gap-3 sm:items-end"><div className="text-left text-sm sm:text-right"><b>{money(i.estimatedImpact)}</b><p className="text-xs text-[#71807b]">estimated impact · {stageLabel[i.stage]}</p></div>{isPrimaryIncident && activePlan?.approvalState === "pending" && <button onClick={() => onReviewPlan(activePlan.id)} className="rounded-lg bg-[#0b7262] px-4 py-2 text-xs font-bold text-white shadow-sm hover:bg-[#095f52]">Review Recovery Plan</button>}</div></div>;
    })}</div> }
  };
  const item = content[page as Exclude<Page, "Overview">];
  return <><div className="mb-6"><h2 className="text-2xl font-bold tracking-tight">{item.title}</h2><p className="mt-1 text-sm text-[#71807b]">{item.subtitle}</p></div><Panel title={item.title}>{item.rows}</Panel></>;
}
function Table({ children }: { children: React.ReactNode }) { return <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left">{children}</table></div>; }
function Th({ children }: { children: React.ReactNode }) { return <th className="whitespace-nowrap border-b border-[#edf0ee] bg-[#fbfcfb] px-5 py-3 text-[10px] font-bold uppercase tracking-[.11em] text-[#71807b]">{children}</th>; }
function Td({ children }: { children: React.ReactNode }) { return <td className="whitespace-nowrap border-b border-[#f0f2f1] px-5 py-3.5 text-sm text-[#4d5b56] last:border-0">{typeof children === "object" ? children : children}</td>; }
